version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    # volumes: 
    #   - ./db:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: true # default
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - 9001:9001
      - 9000:9000
    entrypoint: 'sh'
    command:
      -c "mkdir -p /data/manifests && minio server /data --console-address ':9001'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file:
      - path: .env
        required: true # default
  minio-mc:
    container_name: minio-mc
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000  access-key secret-key;
      /usr/bin/mc mb myminio/manifests;
      /usr/bin/mc anonymous set public myminio/manifests;
      "
    env_file:
      - path: .env
        required: true # default
  # job-launcher:
  #   container_name: job-launcher
  #   restart: unless-stopped
  #   build:
  #     context: ../../../../
  #     dockerfile: packages/apps/job-launcher/server/Dockerfile
  #   expose:
  #     - '${PORT}'
  #   ports:
  #     - '${LOCAL_PORT}:${PORT}'
  #   env_file:
  #     - path: ./.env.development
  #       required: true # default
