version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_USER=operator
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=job-launcher
      - POSTGRES_PORT=5435
      - POSTGRES_SYNC=false
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5435:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data