export enum ReputationOracleEndpoints {
  WORKER_SIGNUP = 'WORKER_SIGNUP',
  WORKER_SIGNIN = 'WORKER_SIGNIN',
  OPERATOR_SIGNUP = 'OPERATOR_SIGNUP',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  RESEND_EMAIL_VERIFICATION = 'RESEND_EMAIL_VERIFICATION',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESTORE_PASSWORD = 'RESTORE_PASSWORD',
  PREPARE_SIGNATURE = 'PREPARE_SIGNATURE',
  DISABLE_OPERATOR = 'DISABLE_OPERATOR',
  KYC_PROCEDURE_START = 'KYC_PROCEDURE_START',
}