import { KVStoreClient, KVStoreKeys, Role } from '@human-protocol/sdk';
import { Wallet, ethers } from 'ethers';

export async function setup(): Promise<void> {
  //This private key is generated by hardhat and should be used just for local testing
  const privateKey =
    '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6'; //0x90F79bf6EB2c4f870365E785982E1f101E93b906
  const provider = new ethers.JsonRpcProvider('http://localhost:8545');
  const wallet = new Wallet(privateKey, provider);

  const kvStoreClient = await KVStoreClient.build(wallet);
  await kvStoreClient.setBulk(
    [KVStoreKeys.role, KVStoreKeys.fee, KVStoreKeys.webhookUrl],
    [Role.RecordingOracle, '1', 'http://localhost:5002/webhook'],
  );
}
