import { PGPConfigService } from '../../config/pgp-config.service';

const MOCK_PGP_PRIVATE_KEY = `-----BEGIN PGP PRIVATE KEY BLOCK-----

xYYEZ/PrtRYJKwYBBAHaRw8BAQdAWlGjcXBBr1TwzGzF+E0oSAKEhdOWZZJY
3sV1Q7B9H7X+CQMIVAJSFQVME6/gJojwvBLoXiuenyRUKksB2Yn6b7qhqwwN
KC6totBcjZ4KtXphI70km6nUrsXcQx3mBPCRvv3iHu0AEBe8ycu4EZQas8wT
/s0AwowEEBYKAD4Fgmfz67UECwkHCAmQ4GfpVirC2ywDFQgKBBYAAgECGQEC
mwMCHgEWIQSLFWF4tiIngAuTpU7gZ+lWKsLbLAAAS78BAJBta8AVTUYog2e3
Ua0G1xM5pMwa6onmvaIV+Pkf6ORAAP4j6cOica1IXQxfGdDM8MOHYCmBW/md
WUhm2FOxxPXLAceLBGfz67USCisGAQQBl1UBBQEBB0CHCsrYq6frR5Hsifml
n4h8Y2yILNkc206x1EEqlktffwMBCAf+CQMIOqE1FTRl5ELgyfjru5Z42l2P
Kws83a9NqyqXDcZ7OCPsDhF0qwb/vMm8AqTGxoIISkY+Dv/nCAk6cRBZUNJY
fArPJ/3hxYE+gurRcSSqGcJ4BBgWCgAqBYJn8+u1CZDgZ+lWKsLbLAKbDBYh
BIsVYXi2IieAC5OlTuBn6VYqwtssAABdoQD9Hd2ykbBrYa/fz4mkPjMxqja5
XxVvDcQ2N304ifl8lOMBAPamPVb8R5LKzRkeGBFcBYdvHf/DI1k9nmQrzv4u
qCMA
=Ytug
-----END PGP PRIVATE KEY BLOCK-----`;

const MOCK_PGP_PASSPHRASE = 'mock-pgp-key-pair';

export const MOCK_PGP_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEZ/PrtRYJKwYBBAHaRw8BAQdAWlGjcXBBr1TwzGzF+E0oSAKEhdOWZZJY
3sV1Q7B9H7XNAMKMBBAWCgA+BYJn8+u1BAsJBwgJkOBn6VYqwtssAxUICgQW
AAIBAhkBApsDAh4BFiEEixVheLYiJ4ALk6VO4GfpVirC2ywAAEu/AQCQbWvA
FU1GKINnt1GtBtcTOaTMGuqJ5r2iFfj5H+jkQAD+I+nDonGtSF0MXxnQzPDD
h2ApgVv5nVlIZthTscT1ywHOOARn8+u1EgorBgEEAZdVAQUBAQdAhwrK2Kun
60eR7In5pZ+IfGNsiCzZHNtOsdRBKpZLX38DAQgHwngEGBYKACoFgmfz67UJ
kOBn6VYqwtssApsMFiEEixVheLYiJ4ALk6VO4GfpVirC2ywAAF2hAP0d3bKR
sGthr9/PiaQ+MzGqNrlfFW8NxDY3fTiJ+XyU4wEA9qY9VvxHksrNGR4YEVwF
h28d/8MjWT2eZCvO/i6oIwA=
=G+WF
-----END PGP PUBLIC KEY BLOCK-----`;

export const mockPgpConfigService: Omit<PGPConfigService, 'configService'> = {
  encrypt: true,
  privateKey: MOCK_PGP_PRIVATE_KEY,
  passphrase: MOCK_PGP_PASSPHRASE,
};
