"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_STATUS_UPDATES_QUERY = exports.GET_ESCROWS_QUERY = exports.GET_ESCROW_BY_ADDRESS_QUERY = void 0;
var graphql_tag_1 = require("graphql-tag");
var ESCROW_FRAGMENT = (0, graphql_tag_1.default)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  fragment EscrowFields on Escrow {\n    address\n    amountPaid\n    balance\n    count\n    factoryAddress\n    finalResultsUrl\n    id\n    intermediateResultsUrl\n    jobRequesterId\n    launcher\n    manifestHash\n    manifestUrl\n    recordingOracle\n    recordingOracleFee\n    reputationOracle\n    reputationOracleFee\n    exchangeOracle\n    exchangeOracleFee\n    status\n    token\n    totalFundedAmount\n    createdAt\n  }\n"], ["\n  fragment EscrowFields on Escrow {\n    address\n    amountPaid\n    balance\n    count\n    factoryAddress\n    finalResultsUrl\n    id\n    intermediateResultsUrl\n    jobRequesterId\n    launcher\n    manifestHash\n    manifestUrl\n    recordingOracle\n    recordingOracleFee\n    reputationOracle\n    reputationOracleFee\n    exchangeOracle\n    exchangeOracleFee\n    status\n    token\n    totalFundedAmount\n    createdAt\n  }\n"])));
var GET_ESCROW_BY_ADDRESS_QUERY = function () { return (0, graphql_tag_1.default)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query getEscrowByAddress($escrowAddress: String!) {\n    escrow(id: $escrowAddress) {\n      ...EscrowFields\n    }\n  }\n  ", "\n"], ["\n  query getEscrowByAddress($escrowAddress: String!) {\n    escrow(id: $escrowAddress) {\n      ...EscrowFields\n    }\n  }\n  ", "\n"])), ESCROW_FRAGMENT); };
exports.GET_ESCROW_BY_ADDRESS_QUERY = GET_ESCROW_BY_ADDRESS_QUERY;
var GET_ESCROWS_QUERY = function (filter) {
    var launcher = filter.launcher, jobRequesterId = filter.jobRequesterId, reputationOracle = filter.reputationOracle, recordingOracle = filter.recordingOracle, exchangeOracle = filter.exchangeOracle, status = filter.status, from = filter.from, to = filter.to;
    var WHERE_CLAUSE = "\n    where: {\n      ".concat(launcher ? "launcher: $launcher," : '', "\n      ").concat(jobRequesterId ? "jobRequesterId: $jobRequesterId," : '', "\n      ").concat(reputationOracle ? "reputationOracle: $reputationOracle," : '', "\n      ").concat(recordingOracle ? "recordingOracle: $recordingOracle," : '', "\n      ").concat(exchangeOracle ? "exchangeOracle: $exchangeOracle," : '', "\n      ").concat(status !== undefined ? "status: $status," : '', "\n      ").concat(from ? "createdAt_gte: $from," : '', "\n      ").concat(to ? "createdAt_lte: $to," : '', "\n    }\n  ");
    return (0, graphql_tag_1.default)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    query getEscrows(\n      $launcher: String\n      $jobRequesterId: String\n      $reputationOracle: String\n      $recordingOracle: String\n      $exchangeOracle: String\n      $status: String\n      $from: Int\n      $to: Int\n      $orderDirection: String\n      $first: Int\n      $skip: Int\n    ) {\n      escrows(\n        ", "\n        orderBy: createdAt,\n        orderDirection: $orderDirection,\n        first: $first,\n        skip: $skip\n      ) {\n        ...EscrowFields\n      }\n    }\n    ", "\n  "], ["\n    query getEscrows(\n      $launcher: String\n      $jobRequesterId: String\n      $reputationOracle: String\n      $recordingOracle: String\n      $exchangeOracle: String\n      $status: String\n      $from: Int\n      $to: Int\n      $orderDirection: String\n      $first: Int\n      $skip: Int\n    ) {\n      escrows(\n        ", "\n        orderBy: createdAt,\n        orderDirection: $orderDirection,\n        first: $first,\n        skip: $skip\n      ) {\n        ...EscrowFields\n      }\n    }\n    ", "\n  "])), WHERE_CLAUSE, ESCROW_FRAGMENT);
};
exports.GET_ESCROWS_QUERY = GET_ESCROWS_QUERY;
var GET_STATUS_UPDATES_QUERY = function (from, to, launcher) {
    var WHERE_CLAUSE = "\n    where: {\n      status_in: $status\n      ".concat(from ? "timestamp_gte: $from" : '', "\n      ").concat(to ? "timestamp_lte: $to" : '', "\n      ").concat(launcher ? "launcher: $launcher" : '', "\n    }\n  ");
    return (0, graphql_tag_1.default)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    query getStatus(\n      $status: [String!]!\n      $from: Int\n      $to: Int\n      $launcher: String\n      $orderDirection: String\n      $first: Int\n      $skip: Int\n    ) {\n      escrowStatusEvents(\n        ", "\n        orderBy: timestamp,\n        orderDirection: $orderDirection,\n        first: $first,\n        skip: $skip\n      ) {\n        escrowAddress,\n        timestamp,\n        status,\n      }\n    }\n  "], ["\n    query getStatus(\n      $status: [String!]!\n      $from: Int\n      $to: Int\n      $launcher: String\n      $orderDirection: String\n      $first: Int\n      $skip: Int\n    ) {\n      escrowStatusEvents(\n        ", "\n        orderBy: timestamp,\n        orderDirection: $orderDirection,\n        first: $first,\n        skip: $skip\n      ) {\n        escrowAddress,\n        timestamp,\n        status,\n      }\n    }\n  "])), WHERE_CLAUSE);
};
exports.GET_STATUS_UPDATES_QUERY = GET_STATUS_UPDATES_QUERY;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
