"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_EVENT_DAY_DATA_QUERY = exports.GET_ESCROW_STATISTICS_QUERY = exports.GET_HMTOKEN_STATISTICS_QUERY = void 0;
var graphql_tag_1 = require("graphql-tag");
var HMTOKEN_STATISTICS_FRAGMENT = (0, graphql_tag_1.default)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  fragment HMTokenStatisticsFields on HMTokenStatistics {\n    totalTransferEventCount\n    totalBulkTransferEventCount\n    totalApprovalEventCount\n    totalBulkApprovalEventCount\n    totalValueTransfered\n    holders\n  }\n"], ["\n  fragment HMTokenStatisticsFields on HMTokenStatistics {\n    totalTransferEventCount\n    totalBulkTransferEventCount\n    totalApprovalEventCount\n    totalBulkApprovalEventCount\n    totalValueTransfered\n    holders\n  }\n"])));
var ESCROW_STATISTICS_FRAGMENT = (0, graphql_tag_1.default)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  fragment EscrowStatisticsFields on EscrowStatistics {\n    fundEventCount\n    setupEventCount\n    storeResultsEventCount\n    bulkPayoutEventCount\n    pendingStatusEventCount\n    cancelledStatusEventCount\n    partialStatusEventCount\n    paidStatusEventCount\n    completedStatusEventCount\n    totalEventCount\n    totalEscrowCount\n  }\n"], ["\n  fragment EscrowStatisticsFields on EscrowStatistics {\n    fundEventCount\n    setupEventCount\n    storeResultsEventCount\n    bulkPayoutEventCount\n    pendingStatusEventCount\n    cancelledStatusEventCount\n    partialStatusEventCount\n    paidStatusEventCount\n    completedStatusEventCount\n    totalEventCount\n    totalEscrowCount\n  }\n"])));
var EVENT_DAY_DATA_FRAGMENT = (0, graphql_tag_1.default)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  fragment EventDayDataFields on EventDayData {\n    timestamp\n    dailyFundEventCount\n    dailySetupEventCount\n    dailyStoreResultsEventCount\n    dailyBulkPayoutEventCount\n    dailyPendingStatusEventCount\n    dailyCancelledStatusEventCount\n    dailyPartialStatusEventCount\n    dailyPaidStatusEventCount\n    dailyCompletedStatusEventCount\n    dailyTotalEventCount\n    dailyEscrowCount\n    dailyWorkerCount\n    dailyPayoutCount\n    dailyPayoutAmount\n    dailyHMTTransferCount\n    dailyHMTTransferAmount\n    dailyUniqueSenders\n    dailyUniqueReceivers\n  }\n"], ["\n  fragment EventDayDataFields on EventDayData {\n    timestamp\n    dailyFundEventCount\n    dailySetupEventCount\n    dailyStoreResultsEventCount\n    dailyBulkPayoutEventCount\n    dailyPendingStatusEventCount\n    dailyCancelledStatusEventCount\n    dailyPartialStatusEventCount\n    dailyPaidStatusEventCount\n    dailyCompletedStatusEventCount\n    dailyTotalEventCount\n    dailyEscrowCount\n    dailyWorkerCount\n    dailyPayoutCount\n    dailyPayoutAmount\n    dailyHMTTransferCount\n    dailyHMTTransferAmount\n    dailyUniqueSenders\n    dailyUniqueReceivers\n  }\n"])));
exports.GET_HMTOKEN_STATISTICS_QUERY = (0, graphql_tag_1.default)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  query GetHMTokenStatistics {\n    hmtokenStatistics(id: \"hmt-statistics-id\") {\n      ...HMTokenStatisticsFields\n    }\n  }\n  ", "\n"], ["\n  query GetHMTokenStatistics {\n    hmtokenStatistics(id: \"hmt-statistics-id\") {\n      ...HMTokenStatisticsFields\n    }\n  }\n  ", "\n"])), HMTOKEN_STATISTICS_FRAGMENT);
exports.GET_ESCROW_STATISTICS_QUERY = (0, graphql_tag_1.default)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  query GetEscrowStatistics {\n    escrowStatistics(id: \"escrow-statistics-id\") {\n      ...EscrowStatisticsFields\n    }\n  }\n  ", "\n"], ["\n  query GetEscrowStatistics {\n    escrowStatistics(id: \"escrow-statistics-id\") {\n      ...EscrowStatisticsFields\n    }\n  }\n  ", "\n"])), ESCROW_STATISTICS_FRAGMENT);
var GET_EVENT_DAY_DATA_QUERY = function (params) {
    var from = params.from, to = params.to, limit = params.limit;
    var WHERE_CLAUSE = "\n    where: {\n      ".concat(from !== undefined ? "timestamp_gte: $from" : '', "\n      ").concat(to !== undefined ? "timestamp_lte: $to" : '', "\n    }\n  ");
    var LIMIT_CLAUSE = "\n    first: ".concat(limit ? "$limit" : "1000", "\n  ");
    return (0, graphql_tag_1.default)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    query GetEscrowDayData($from: Int, $to: Int) {\n      eventDayDatas(\n        ", ",\n        orderBy: timestamp,\n        orderDirection: desc,\n        ", "\n      ) {\n        ...EventDayDataFields\n      }\n    }\n    ", "\n  "], ["\n    query GetEscrowDayData($from: Int, $to: Int) {\n      eventDayDatas(\n        ", ",\n        orderBy: timestamp,\n        orderDirection: desc,\n        ", "\n      ) {\n        ...EventDayDataFields\n      }\n    }\n    ", "\n  "])), WHERE_CLAUSE, LIMIT_CLAUSE, EVENT_DAY_DATA_FRAGMENT);
};
exports.GET_EVENT_DAY_DATA_QUERY = GET_EVENT_DAY_DATA_QUERY;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
