version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
        # Ignore versions of Jest and related packages that are equal to
        # or greater than 30.0.0 because it introduces module system change
        # and it must be updated together with some other packages (nest, ts-jest, etc.)
        # including some extra configuration changes
      - dependency-name: "*jest*"
        versions: [">=30.0.0"]

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # Maintain dependencies for rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
