[package]
name = "rewards-pool-mock"
version = "0.1.0"
authors = [
    "Vlad Nedelcu <vlad.nedelcu@buidly.com>"
]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.multiversx-sc]
version = "0.43.3"

[dev-dependencies.multiversx-sc-scenario]
version = "0.43.3"
