export const routerPaths = {
  homePage: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  resetPassword: '/reset-password',
  resetPasswordSuccess: '/reset-password-success',
  sendResetLink: '/send-reset-link',
  sendResetLinkSuccess: '/send-reset-link-success',
  emailVerification: '/verify',
  verifyEmail: '/verify-email',
  verifyUser: '/verify-user',
  profile: '/profile',
  jobsDiscovery: '/jobs-discovery',
  jobs: '/jobs-discovery',
  myJobs: '/my-jobs',
  HcaptchaLabeling: '/hcaptcha-labeling',
  enableLabeler: '/enable-labeler',
  registrationInExchangeOracle: '/registration-in-exchange-oracle',
} as const;
