version: '3.8'
services:
  redis-docker:
    image: redis
    ports:
      - 6379:6379
  vote-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis-docker
    env_file:
      - ./.env
