export enum JobStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  LAUNCHED = 'LAUNCHED',
  FAILED = 'FAILED',
  TO_CANCEL = 'TO_CANCEL',
  CANCELED = 'CANCELED',
}

export enum JobRequestType {
  IMAGE_LABEL_BINARY = 'IMAGE_LABEL_BINARY',
  FORTUNE = 'FORTUNE',
}
