export enum JobStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  LAUNCHING = 'LAUNCHING',
  FUNDING = 'FUNDING',
  LAUNCHED = 'LAUNCHED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  TO_CANCEL = 'TO_CANCEL',
  CANCELED = 'CANCELED',
}

export enum JobStatusFilter {
  PENDING = 'PENDING',
  LAUNCHED = 'LAUNCHED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}

export enum JobRequestType {
  IMAGE_POINTS = 'IMAGE_POINTS',
  IMAGE_BOXES = 'IMAGE_BOXES',
  FORTUNE = 'FORTUNE',
}
