services:
- type: web
  name: fortune-exchange-oracle
  runtime: node
  repo: https://github.com/humanprotocol/human-protocol
  branch: feat/exchange/create-job
  plan: free
  envVars:
  - key: WEB3_PRIVATE_KEY
    sync: false
  - key: S3_SECRET_KEY
    sync: false
  - key: S3_PORT
    sync: false
  - key: S3_ENDPOINT
    sync: false
  - key: S3_ACCESS_KEY
    sync: false
  - key: POSTGRES_URL
    fromDatabase:
      name: stg-fortune-exchange-oracle
      property: connectionString
  - key: PORT
    sync: false
  - key: PGP_ENCRYPT
    sync: false
  - key: NODE_VERSION
    sync: false
  - key: NODE_ENV
    sync: false
  - key: HOST
    sync: false
  region: frankfurt
  buildCommand: yarn install; yarn workspace @human-protocol/sdk build; yarn build
  startCommand: yarn start:prod
  # preDeployCommand: yarn migration:run
  pullRequestPreviewsEnabled: true
  rootDir: packages/apps/fortune/exchange-oracle/server
databases:
- name: stg-fortune-exchange-oracle
  databaseName: stg_fortune_exchange_oracle
  user: stg_fortune_exchange_oracle_user
  plan: free
  region: frankfurt
  ipAllowList: []
  postgresMajorVersion: "16"
version: "1"