// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escrow
    (
        setup
        cancel
        abort
        complete
        storeResults
        getIntermediateResults
        getFinalResults
        bulkPayOut
        getOracles
        deposit
        addTrustedHandlers
        getBalance
        getToken
        getStatus
        getExpiration
        getManifest
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
