export const PAYMENT_SIGNATURE_KEY = 'human-signature';

export const CURRENCY = {
  hmt: 'hmt',
  usd: 'usd',
};

export const paymentType: { [key: string]: string } = {
  deposit: 'Deposit',
  refund: 'Refund',
  withdrawal: 'Launch Job',
  slash: 'Slash',
};

export const paymentSource: { [key: string]: string } = {
  fiat: 'Credit Card',
  crypto: 'Crypto',
  balance: 'Balance',
};

export enum Country {
  AF = 'af',
  AL = 'al',
  DZ = 'dz',
  AS = 'as',
  AD = 'ad',
  AO = 'ao',
  AI = 'ai',
  AQ = 'aq',
  AG = 'ag',
  AR = 'ar',
  AM = 'am',
  AW = 'aw',
  AC = 'ac',
  AU = 'au',
  AT = 'at',
  AZ = 'az',
  BS = 'bs',
  BH = 'bh',
  BD = 'bd',
  BB = 'bb',
  BY = 'by',
  BE = 'be',
  BZ = 'bz',
  BJ = 'bj',
  BM = 'bm',
  BT = 'bt',
  BO = 'bo',
  BQ = 'bq',
  BA = 'ba',
  BW = 'bw',
  BV = 'bv',
  BR = 'br',
  IO = 'io',
  BN = 'bn',
  BG = 'bg',
  BF = 'bf',
  BI = 'bi',
  KH = 'kh',
  CM = 'cm',
  CA = 'ca',
  IC = 'ic',
  CV = 'cv',
  KY = 'ky',
  CF = 'cf',
  EA = 'ea',
  TD = 'td',
  CL = 'cl',
  CN = 'cn',
  CX = 'cx',
  CP = 'cp',
  CC = 'cc',
  CO = 'co',
  KM = 'km',
  CK = 'ck',
  CR = 'cr',
  CI = 'ci',
  HR = 'hr',
  CU = 'cu',
  CW = 'cw',
  CY = 'cy',
  CZ = 'cz',
  CD = 'cd',
  DK = 'dk',
  DG = 'dg',
  DJ = 'dj',
  DM = 'dm',
  DO = 'do',
  TL = 'tl',
  EC = 'ec',
  EG = 'eg',
  SV = 'sv',
  GQ = 'gq',
  ER = 'er',
  EE = 'ee',
  ET = 'et',
  EU = 'eu',
  FK = 'fk',
  FO = 'fo',
  FJ = 'fj',
  FI = 'fi',
  FR = 'fr',
  FX = 'fx',
  GF = 'gf',
  PF = 'pf',
  TF = 'tf',
  GA = 'ga',
  GM = 'gm',
  GE = 'ge',
  DE = 'de',
  GH = 'gh',
  GI = 'gi',
  GR = 'gr',
  GL = 'gl',
  GD = 'gd',
  GP = 'gp',
  GU = 'gu',
  GT = 'gt',
  GG = 'gg',
  GN = 'gn',
  GW = 'gw',
  GY = 'gy',
  HT = 'ht',
  HM = 'hm',
  HN = 'hn',
  HK = 'hk',
  HU = 'hu',
  IS = 'is',
  IN = 'in',
  ID = 'id',
  IR = 'ir',
  IQ = 'iq',
  IE = 'ie',
  IM = 'im',
  IL = 'il',
  IT = 'it',
  JM = 'jm',
  JP = 'jp',
  JE = 'je',
  JO = 'jo',
  KZ = 'kz',
  KE = 'ke',
  KI = 'ki',
  KP = 'kp',
  KR = 'kr',
  KW = 'kw',
  KG = 'kg',
  LA = 'la',
  LV = 'lv',
  LB = 'lb',
  LS = 'ls',
  LR = 'lr',
  LY = 'ly',
  LI = 'li',
  LT = 'lt',
  LU = 'lu',
  MO = 'mo',
  MK = 'mk',
  MG = 'mg',
  MW = 'mw',
  MY = 'my',
  ML = 'ml',
  MT = 'mt',
  MH = 'mh',
  MQ = 'mq',
  MR = 'mr',
  MU = 'mu',
  YT = 'yt',
  MX = 'mx',
  FM = 'fm',
  MD = 'md',
  MC = 'mc',
  MN = 'mn',
  ME = 'me',
  MS = 'ms',
  MA = 'ma',
  MZ = 'mz',
  MM = 'mm',
  NA = 'na',
  NR = 'nr',
  NP = 'np',
  NL = 'nl',
  NC = 'nc',
  NZ = 'nz',
  NI = 'ni',
  NE = 'ne',
  NG = 'ng',
  NU = 'nu',
  NF = 'nf',
  MP = 'mp',
  NO = 'no',
  OM = 'om',
  PK = 'pk',
  PW = 'pw',
  PS = 'ps',
  PA = 'pa',
  PG = 'pg',
  PY = 'py',
  PE = 'pe',
  PH = 'ph',
  PN = 'pn',
  PL = 'pl',
  PT = 'pt',
  PR = 'pr',
  QA = 'qa',
  RE = 're',
  RO = 'ro',
  RU = 'ru',
  RW = 'rw',
  BL = 'bl',
  SH = 'sh',
  KN = 'kn',
  LC = 'lc',
  MF = 'mf',
  PM = 'pm',
  VC = 'vc',
  WS = 'ws',
  SM = 'sm',
  ST = 'st',
  SA = 'sa',
  SN = 'sn',
  RS = 'rs',
  SC = 'sc',
  SL = 'sl',
  SG = 'sg',
  SX = 'sx',
  SK = 'sk',
  SI = 'si',
  SB = 'sb',
  SO = 'so',
  ZA = 'za',
  GS = 'gs',
  SS = 'ss',
  ES = 'es',
  LK = 'lk',
  SD = 'sd',
  SR = 'sr',
  SJ = 'sj',
  SZ = 'sz',
  SE = 'se',
  CH = 'ch',
  SY = 'sy',
  TW = 'tw',
  TJ = 'tj',
  TZ = 'tz',
  TH = 'th',
  TG = 'tg',
  TK = 'tk',
  TO = 'to',
  TT = 'tt',
  TN = 'tn',
  TR = 'tr',
  TM = 'tm',
  TC = 'tc',
  TV = 'tv',
  UG = 'ug',
  UA = 'ua',
  AE = 'ae',
  GB = 'gb',
  US = 'us',
  UM = 'um',
  UY = 'uy',
  UZ = 'uz',
  VU = 'vu',
  VA = 'va',
  VE = 've',
  VN = 'vn',
  WF = 'wf',
  EH = 'eh',
  YE = 'ye',
  ZM = 'zm',
  ZW = 'zw',
}

export const countryOptions: { [key: string]: string } = {
  [Country.AF]: 'Afghanistan',
  [Country.AL]: 'Albania',
  [Country.DZ]: 'Algeria',
  [Country.AS]: 'American Samoa',
  [Country.AD]: 'Andorra',
  [Country.AO]: 'Angola',
  [Country.AI]: 'Anguilla',
  [Country.AQ]: 'Antarctica',
  [Country.AG]: 'Antigua and Barbuda',
  [Country.AR]: 'Argentina',
  [Country.AM]: 'Armenia',
  [Country.AW]: 'Aruba',
  [Country.AC]: 'Ascension Island',
  [Country.AU]: 'Australia',
  [Country.AT]: 'Austria',
  [Country.AZ]: 'Azerbaijan',
  [Country.BS]: 'Bahamas',
  [Country.BH]: 'Bahrain',
  [Country.BD]: 'Bangladesh',
  [Country.BB]: 'Barbados',
  [Country.BY]: 'Belarus',
  [Country.BE]: 'Belgium',
  [Country.BZ]: 'Belize',
  [Country.BJ]: 'Benin',
  [Country.BM]: 'Bermuda',
  [Country.BT]: 'Bhutan',
  [Country.BO]: 'Bolivia',
  [Country.BQ]: 'Bonaire, Sint Eustatius and Saba',
  [Country.BA]: 'Bosnia and Herzegovina',
  [Country.BW]: 'Botswana',
  [Country.BV]: 'Bouvet Island',
  [Country.BR]: 'Brazil',
  [Country.IO]: 'British Indian Ocean Territory',
  [Country.BN]: 'Brunei Darussalam',
  [Country.BG]: 'Bulgaria',
  [Country.BF]: 'Burkina Faso',
  [Country.BI]: 'Burundi',
  [Country.KH]: 'Cambodia',
  [Country.CM]: 'Cameroon',
  [Country.CA]: 'Canada',
  [Country.IC]: 'Canary Islands',
  [Country.CV]: 'Cape Verde',
  [Country.KY]: 'Cayman Islands',
  [Country.CF]: 'Central African Republic',
  [Country.EA]: 'Ceuta and Melilla',
  [Country.TD]: 'Chad',
  [Country.CL]: 'Chile',
  [Country.CN]: 'China',
  [Country.CX]: 'Christmas Island',
  [Country.CP]: 'Clipperton Island',
  [Country.CC]: 'Cocos (Keeling) Islands',
  [Country.CO]: 'Colombia',
  [Country.KM]: 'Comoros',
  [Country.CK]: 'Cook Islands',
  [Country.CR]: 'Costa Rica',
  [Country.CI]: "Côte d'Ivoire",
  [Country.HR]: 'Croatia',
  [Country.CU]: 'Cuba',
  [Country.CW]: 'Curaçao',
  [Country.CY]: 'Cyprus',
  [Country.CZ]: 'Czechia',
  [Country.CD]: 'Democratic Republic of the Congo',
  [Country.DK]: 'Denmark',
  [Country.DG]: 'Diego Garcia',
  [Country.DJ]: 'Djibouti',
  [Country.DM]: 'Dominica',
  [Country.DO]: 'Dominican Republic',
  [Country.TL]: 'Timor-Leste',
  [Country.EC]: 'Ecuador',
  [Country.EG]: 'Egypt',
  [Country.SV]: 'El Salvador',
  [Country.GQ]: 'Equatorial Guinea',
  [Country.ER]: 'Eritrea',
  [Country.EE]: 'Estonia',
  [Country.ET]: 'Ethiopia',
  [Country.EU]: 'European Union',
  [Country.FK]: 'Falkland Islands',
  [Country.FO]: 'Faroe Islands',
  [Country.FJ]: 'Fiji',
  [Country.FI]: 'Finland',
  [Country.FR]: 'France',
  [Country.FX]: 'Metropolitan France',
  [Country.GF]: 'French Guiana',
  [Country.PF]: 'French Polynesia',
  [Country.TF]: 'French Southern Territories',
  [Country.GA]: 'Gabon',
  [Country.GM]: 'Gambia',
  [Country.GE]: 'Georgia',
  [Country.DE]: 'Germany',
  [Country.GH]: 'Ghana',
  [Country.GI]: 'Gibraltar',
  [Country.GR]: 'Greece',
  [Country.GL]: 'Greenland',
  [Country.GD]: 'Grenada',
  [Country.GP]: 'Guadeloupe',
  [Country.GU]: 'Guam',
  [Country.GT]: 'Guatemala',
  [Country.GG]: 'Guernsey',
  [Country.GN]: 'Guinea',
  [Country.GW]: 'Guinea-Bissau',
  [Country.GY]: 'Guyana',
  [Country.HT]: 'Haiti',
  [Country.HM]: 'Heard Island and McDonald Islands',
  [Country.HN]: 'Honduras',
  [Country.HK]: 'Hong Kong',
  [Country.HU]: 'Hungary',
  [Country.IS]: 'Iceland',
  [Country.IN]: 'India',
  [Country.ID]: 'Indonesia',
  [Country.IR]: 'Iran',
  [Country.IQ]: 'Iraq',
  [Country.IE]: 'Ireland',
  [Country.IM]: 'Isle of Man',
  [Country.IL]: 'Israel',
  [Country.IT]: 'Italy',
  [Country.JM]: 'Jamaica',
  [Country.JP]: 'Japan',
  [Country.JE]: 'Jersey',
  [Country.JO]: 'Jordan',
  [Country.KZ]: 'Kazakhstan',
  [Country.KE]: 'Kenya',
  [Country.KI]: 'Kiribati',
  [Country.KP]: 'North Korea',
  [Country.KR]: 'South Korea',
  [Country.KW]: 'Kuwait',
  [Country.KG]: 'Kyrgyzstan',
  [Country.LA]: 'Laos',
  [Country.LV]: 'Latvia',
  [Country.LB]: 'Lebanon',
  [Country.LS]: 'Lesotho',
  [Country.LR]: 'Liberia',
  [Country.LY]: 'Libya',
  [Country.LI]: 'Liechtenstein',
  [Country.LT]: 'Lithuania',
  [Country.LU]: 'Luxembourg',
  [Country.MO]: 'Macao',
  [Country.MK]: 'North Macedonia',
  [Country.MG]: 'Madagascar',
  [Country.MW]: 'Malawi',
  [Country.MY]: 'Malaysia',
  [Country.ML]: 'Mali',
  [Country.MT]: 'Malta',
  [Country.MH]: 'Marshall Islands',
  [Country.MQ]: 'Martinique',
  [Country.MR]: 'Mauritania',
  [Country.MU]: 'Mauritius',
  [Country.YT]: 'Mayotte',
  [Country.MX]: 'Mexico',
  [Country.FM]: 'Micronesia',
  [Country.MD]: 'Moldova',
  [Country.MC]: 'Monaco',
  [Country.MN]: 'Mongolia',
  [Country.ME]: 'Montenegro',
  [Country.MS]: 'Montserrat',
  [Country.MA]: 'Morocco',
  [Country.MZ]: 'Mozambique',
  [Country.MM]: 'Myanmar',
  [Country.NA]: 'Namibia',
  [Country.NR]: 'Nauru',
  [Country.NP]: 'Nepal',
  [Country.NL]: 'Netherlands',
  [Country.NC]: 'New Caledonia',
  [Country.NZ]: 'New Zealand',
  [Country.NI]: 'Nicaragua',
  [Country.NE]: 'Niger',
  [Country.NG]: 'Nigeria',
  [Country.NU]: 'Niue',
  [Country.NF]: 'Norfolk Island',
  [Country.MP]: 'Northern Mariana Islands',
  [Country.NO]: 'Norway',
  [Country.OM]: 'Oman',
  [Country.PK]: 'Pakistan',
  [Country.PW]: 'Palau',
  [Country.PS]: 'Palestine',
  [Country.PA]: 'Panama',
  [Country.PG]: 'Papua New Guinea',
  [Country.PY]: 'Paraguay',
  [Country.PE]: 'Peru',
  [Country.PH]: 'Philippines',
  [Country.PN]: 'Pitcairn Islands',
  [Country.PL]: 'Poland',
  [Country.PT]: 'Portugal',
  [Country.PR]: 'Puerto Rico',
  [Country.QA]: 'Qatar',
  [Country.RE]: 'Réunion',
  [Country.RO]: 'Romania',
  [Country.RU]: 'Russia',
  [Country.RW]: 'Rwanda',
  [Country.BL]: 'Saint Barthélemy',
  [Country.SH]: 'Saint Helena, Ascension and Tristan da Cunha',
  [Country.KN]: 'Saint Kitts and Nevis',
  [Country.LC]: 'Saint Lucia',
  [Country.MF]: 'Saint Martin',
  [Country.PM]: 'Saint Pierre and Miquelon',
  [Country.VC]: 'Saint Vincent and the Grenadines',
  [Country.WS]: 'Samoa',
  [Country.SM]: 'San Marino',
  [Country.ST]: 'Sao Tome and Principe',
  [Country.SA]: 'Saudi Arabia',
  [Country.SN]: 'Senegal',
  [Country.RS]: 'Serbia',
  [Country.SC]: 'Seychelles',
  [Country.SL]: 'Sierra Leone',
  [Country.SG]: 'Singapore',
  [Country.SK]: 'Slovakia',
  [Country.SI]: 'Slovenia',
  [Country.SB]: 'Solomon Islands',
  [Country.SO]: 'Somalia',
  [Country.ZA]: 'South Africa',
  [Country.GS]: 'South Georgia and the South Sandwich Islands',
  [Country.SS]: 'South Sudan',
  [Country.ES]: 'Spain',
  [Country.LK]: 'Sri Lanka',
  [Country.SD]: 'Sudan',
  [Country.SR]: 'Suriname',
  [Country.SJ]: 'Svalbard and Jan Mayen',
  [Country.SE]: 'Sweden',
  [Country.CH]: 'Switzerland',
  [Country.SY]: 'Syria',
  [Country.TW]: 'Taiwan',
  [Country.TJ]: 'Tajikistan',
  [Country.TZ]: 'Tanzania',
  [Country.TH]: 'Thailand',
  [Country.TG]: 'Togo',
  [Country.TK]: 'Tokelau',
  [Country.TO]: 'Tonga',
  [Country.TT]: 'Trinidad and Tobago',
  [Country.TN]: 'Tunisia',
  [Country.TR]: 'Turkey',
  [Country.TM]: 'Turkmenistan',
  [Country.TC]: 'Turks and Caicos Islands',
  [Country.TV]: 'Tuvalu',
  [Country.UG]: 'Uganda',
  [Country.UA]: 'Ukraine',
  [Country.AE]: 'United Arab Emirates',
  [Country.GB]: 'United Kingdom',
  [Country.US]: 'United States',
  [Country.UM]: 'United States Minor Outlying Islands',
  [Country.UY]: 'Uruguay',
  [Country.UZ]: 'Uzbekistan',
  [Country.VU]: 'Vanuatu',
  [Country.VA]: 'Vatican City',
  [Country.VE]: 'Venezuela',
  [Country.VN]: 'Vietnam',
  [Country.WF]: 'Wallis and Futuna',
  [Country.EH]: 'Western Sahara',
  [Country.YE]: 'Yemen',
  [Country.ZM]: 'Zambia',
  [Country.ZW]: 'Zimbabwe',
};

export enum VatType {
  AD_NRT = 'ad_nrt',
  AE_TRN = 'ae_trn',
  AR_CUIT = 'ar_cuit',
  AU_ABN = 'au_abn',
  AU_ARN = 'au_arn',
  BG_UIC = 'bg_uic',
  BH_VAT = 'bh_vat',
  BO_TIN = 'bo_tin',
  BR_CNPJ = 'br_cnpj',
  BR_CPF = 'br_cpf',
  BY_TIN = 'by_tin',
  CA_BN = 'ca_bn',
  CA_GST_HST = 'ca_gst_hst',
  CA_PST_BC = 'ca_pst_bc',
  CA_PST_MB = 'ca_pst_mb',
  CA_PST_SK = 'ca_pst_sk',
  CA_QST = 'ca_qst',
  CH_UID = 'ch_uid',
  CH_VAT = 'ch_vat',
  CL_TIN = 'cl_tin',
  CN_TIN = 'cn_tin',
  CO_NIT = 'co_nit',
  CR_TIN = 'cr_tin',
  DE_STN = 'de_stn',
  DO_RCN = 'do_rcn',
  EC_RUC = 'ec_ruc',
  EG_TIN = 'eg_tin',
  ES_CIF = 'es_cif',
  EU_OSS_VAT = 'eu_oss_vat',
  EU_VAT = 'eu_vat',
  GB_VAT = 'gb_vat',
  GE_VAT = 'ge_vat',
  HK_BR = 'hk_br',
  HR_OIB = 'hr_oib',
  HU_TIN = 'hu_tin',
  ID_NPWP = 'id_npwp',
  IL_VAT = 'il_vat',
  IN_GST = 'in_gst',
  IS_VAT = 'is_vat',
  JP_CN = 'jp_cn',
  JP_RN = 'jp_rn',
  JP_TRN = 'jp_trn',
  KE_PIN = 'ke_pin',
  KR_BRN = 'kr_brn',
  KZ_BIN = 'kz_bin',
  LI_UID = 'li_uid',
  MA_VAT = 'ma_vat',
  MD_VAT = 'md_vat',
  MX_RFC = 'mx_rfc',
  MY_FRP = 'my_frp',
  MY_ITN = 'my_itn',
  MY_SST = 'my_sst',
  NG_TIN = 'ng_tin',
  NO_VAT = 'no_vat',
  NO_VOEC = 'no_voec',
  NZ_GST = 'nz_gst',
  OM_VAT = 'om_vat',
  PE_RUC = 'pe_ruc',
  PH_TIN = 'ph_tin',
  RO_TIN = 'ro_tin',
  RS_PIB = 'rs_pib',
  RU_INN = 'ru_inn',
  RU_KPP = 'ru_kpp',
  SA_VAT = 'sa_vat',
  SG_GST = 'sg_gst',
  SG_UEN = 'sg_uen',
  SI_TIN = 'si_tin',
  SV_NIT = 'sv_nit',
  TH_VAT = 'th_vat',
  TR_TIN = 'tr_tin',
  TW_VAT = 'tw_vat',
  TZ_VAT = 'tz_vat',
  UA_VAT = 'ua_vat',
  US_EIN = 'us_ein',
  UY_RUC = 'uy_ruc',
  UZ_TIN = 'uz_tin',
  UZ_VAT = 'uz_vat',
  VE_RIF = 've_rif',
  VN_TIN = 'vn_tin',
  ZA_VAT = 'za_vat',
}

export const vatTypeOptions: { [key: string]: string } = {
  [VatType.AD_NRT]: 'Andorran NRT',
  [VatType.AE_TRN]: 'UAE TRN',
  [VatType.AR_CUIT]: 'Argentinian CUIT',
  [VatType.AU_ABN]: 'Australian ABN',
  [VatType.AU_ARN]: 'Australian ARN',
  [VatType.BG_UIC]: 'Bulgarian UIC',
  [VatType.BH_VAT]: 'Bahraini VAT',
  [VatType.BO_TIN]: 'Bolivian TIN',
  [VatType.BR_CNPJ]: 'Brazilian CNPJ',
  [VatType.BR_CPF]: 'Brazilian CPF',
  [VatType.BY_TIN]: 'Belarusian TIN',
  [VatType.CA_BN]: 'Canadian BN',
  [VatType.CA_GST_HST]: 'Canadian GST/HST',
  [VatType.CA_PST_BC]: 'Canadian PST BC',
  [VatType.CA_PST_MB]: 'Canadian PST MB',
  [VatType.CA_PST_SK]: 'Canadian PST SK',
  [VatType.CA_QST]: 'Canadian QST',
  [VatType.CH_UID]: 'Swiss UID',
  [VatType.CH_VAT]: 'Swiss VAT',
  [VatType.CL_TIN]: 'Chilean TIN',
  [VatType.CN_TIN]: 'Chinese TIN',
  [VatType.CO_NIT]: 'Colombian NIT',
  [VatType.CR_TIN]: 'Costa Rican TIN',
  [VatType.DE_STN]: 'German STN',
  [VatType.DO_RCN]: 'Dominican RCN',
  [VatType.EC_RUC]: 'Ecuadorian RUC',
  [VatType.EG_TIN]: 'Egyptian TIN',
  [VatType.ES_CIF]: 'Spanish CIF',
  [VatType.EU_OSS_VAT]: 'EU OSS VAT',
  [VatType.EU_VAT]: 'EU VAT',
  [VatType.GB_VAT]: 'British VAT',
  [VatType.GE_VAT]: 'Georgian VAT',
  [VatType.HK_BR]: 'Hong Kong BR',
  [VatType.HR_OIB]: 'Croatian OIB',
  [VatType.HU_TIN]: 'Hungarian TIN',
  [VatType.ID_NPWP]: 'Indonesian NPWP',
  [VatType.IL_VAT]: 'Israeli VAT',
  [VatType.IN_GST]: 'Indian GST',
  [VatType.IS_VAT]: 'Icelandic VAT',
  [VatType.JP_CN]: 'Japanese CN',
  [VatType.JP_RN]: 'Japanese RN',
  [VatType.JP_TRN]: 'Japanese TRN',
  [VatType.KE_PIN]: 'Kenyan PIN',
  [VatType.KR_BRN]: 'South Korean BRN',
  [VatType.KZ_BIN]: 'Kazakh BIN',
  [VatType.LI_UID]: 'Liechtenstein UID',
  [VatType.MA_VAT]: 'Moroccan VAT',
  [VatType.MD_VAT]: 'Moldovan VAT',
  [VatType.MX_RFC]: 'Mexican RFC',
  [VatType.MY_FRP]: 'Malaysian FRP',
  [VatType.MY_ITN]: 'Malaysian ITN',
  [VatType.MY_SST]: 'Malaysian SST',
  [VatType.NG_TIN]: 'Nigerian TIN',
  [VatType.NO_VAT]: 'Norwegian VAT',
  [VatType.NO_VOEC]: 'Norwegian VOEC',
  [VatType.NZ_GST]: 'New Zealand GST',
  [VatType.OM_VAT]: 'Omani VAT',
  [VatType.PE_RUC]: 'Peruvian RUC',
  [VatType.PH_TIN]: 'Philippine TIN',
  [VatType.RO_TIN]: 'Romanian TIN',
  [VatType.RS_PIB]: 'Serbian PIB',
  [VatType.RU_INN]: 'Russian INN',
  [VatType.RU_KPP]: 'Russian KPP',
  [VatType.SA_VAT]: 'Saudi VAT',
  [VatType.SG_GST]: 'Singaporean GST',
  [VatType.SG_UEN]: 'Singaporean UEN',
  [VatType.SI_TIN]: 'Slovenian TIN',
  [VatType.SV_NIT]: 'Salvadoran NIT',
  [VatType.TH_VAT]: 'Thai VAT',
  [VatType.TR_TIN]: 'Turkish TIN',
  [VatType.TW_VAT]: 'Taiwanese VAT',
  [VatType.TZ_VAT]: 'Tanzanian VAT',
  [VatType.UA_VAT]: 'Ukrainian VAT',
  [VatType.US_EIN]: 'American EIN',
  [VatType.UY_RUC]: 'Uruguayan RUC',
  [VatType.UZ_TIN]: 'Uzbek TIN',
  [VatType.UZ_VAT]: 'Uzbek VAT',
  [VatType.VE_RIF]: 'Venezuelan RIF',
  [VatType.VN_TIN]: 'Vietnamese TIN',
  [VatType.ZA_VAT]: 'South African VAT',
};
