version: '3.8'
name: human-protocol
services:
  graph-node-db:
    container_name: graph-node-db
    image: postgres:latest
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5433:5432
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./graph-node-db:/var/lib/postgresql/data
  graph-node:
    container_name: graph-node
    hostname: graph-node
    image: graphprotocol/graph-node
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
      - 8030:8030
      - 8040:8040
    depends_on:
      - ipfs
      - graph-node-db
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: graph-node-db
      postgres_user: user
      postgres_pass: password
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'localhost:http://host.docker.internal:8545'
      GRAPH_LOG: info
  ipfs:
    hostname: ipfs
    image: ipfs/kubo:v0.14.0
    ports:
      - 5010:5001