name: human-protocol-local-web3

x-service-default-config:
  restart: &default-restart unless-stopped
  logging: &default-logging
    options:
      max-size: 10m
      max-file: 3

x-hardcoded-vars:
  graph_db_user: &graph_db_user graph-node
  graph_db_passwrod: &graph_db_passwrod let-me-in
  graph_db_name: &graph_db_name graph-node

services:
  blockchain-node:
    container_name: blockchain-node
    image: human-protocol/hardhat-blockchain-node
    pull_policy: build
    restart: *default-restart
    logging:
      <<: *default-logging
    build: 
      context: ../
      dockerfile: packages/core/Dockerfile.local
    healthcheck:
      test: yarn local:readiness
      interval: 15s
      timeout: 30s
      retries: 0
    networks:
      - human_protocol_web3
    ports:
      - name: node-port
        target: 8545
        published: ${BLOCKCHAIN_NODE_PORT:-8545}

  ipfs:
    container_name: ipfs
    image: ipfs/kubo:v0.14.0
    restart: *default-restart
    logging:
      <<: *default-logging
    healthcheck:
      test: ["CMD-SHELL", "ipfs id > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - human_protocol_web3
    ports:
      - name: ipfs-port
        target: 5001
        published: ${IPFS_PORT:-5010}
    volumes:
      - ipfs-data:/data/ipfs:Z

  graph-node-db:
    container_name: graph-node-db
    image: postgres:latest
    restart: *default-restart
    logging:
      <<: *default-logging
    networks:
      - human_protocol_web3
    ports:
      - name: instance_port
        target: 5432
        published: ${GRAPH_NODE_DB_PORT:-5434}
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - graph-node-db-data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: *graph_db_user
      POSTGRES_PASSWORD: *graph_db_passwrod
      POSTGRES_DB: *graph_db_name
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"

  graph-node:
    container_name: graph-node
    # In case of issues on Mac M1 rebuild the image for it locally
    # https://github.com/graphprotocol/graph-node/blob/master/docker/README.md#running-graph-node-on-an-macbook-m1
    image: graphprotocol/graph-node
    restart: *default-restart
    logging:
      <<: *default-logging
    networks:
      - human_protocol_web3
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - blockchain-node
      - ipfs
      - graph-node-db
    environment:
      postgres_host: graph-node-db
      postgres_user: *graph_db_user
      postgres_pass: *graph_db_passwrod
      postgres_db: *graph_db_name
      ipfs: ipfs:5001
      ethereum: localhost:http://blockchain-node:8545
      GRAPH_LOG: info

volumes:
  ipfs-data:
  graph-node-db-data:

networks:
  human_protocol_web3:
    name: human-protocol-web3
