repos:
  -   repo: local
      hooks:
        - id: lint
          name: lint
          entry: ruff check --fix --unsafe-fixes --show-fixes
          language: system
          require_serial: true
          files: "^packages/examples/cvat/exchange-oracle/.*"
          types: [python]
        - id: format
          name: format
          entry: ruff format
          require_serial: true
          language: system
          files: "^packages/examples/cvat/exchange-oracle/.*"
          types: [python]
