import { FortuneJobType } from '../src/common/enums/job';
import { Web3Env } from '../src/common/enums/web3';
import { FortuneManifestDto } from '../src/modules/manifest/manifest.dto';

export const MOCK_REQUESTER_TITLE = 'Mock job title';
export const MOCK_REQUESTER_DESCRIPTION = 'Mock job description';
export const MOCK_ADDRESS = '0xCf88b3f1992458C2f5a229573c768D0E9F70C44e';
export const MOCK_FILE_URL = 'http://mockedFileUrl.test/bucket/file.json';
export const MOCK_FILE_HASH = 'mockedFileHash';
export const MOCK_PRIVATE_KEY =
  'd334daf65a631f40549cc7de126d5a0016f32a2d00c49f94563f9737f7135e55';
export const MOCK_WEB3_RPC_URL = 'http://localhost:8545';
export const MOCK_EXCHANGE_ORACLE_ADDRESS =
  '0xCf88b3f1992458C2f5a229573c768D0E9F70C44e';
export const MOCK_EXCHANGE_ORACLE_WEBHOOK_URL = 'http://localhost:3000';
export const MOCK_REPUTATION_ORACLE_URL = 'http://reporacle:3000';
export const MOCK_RECORDING_ORACLE_URL = 'http://recoracle:3000';
export const MOCK_EXCHANGE_ORACLE_URL = 'http://exoracle:3000';
export const MOCK_SECRET = 'secrete';
export const MOCK_TRANSACTION_HASH =
  '0xd28e4c40571530afcb25ea1890e77b2d18c35f06049980ca4fb71829f64d89dc';
export const MOCK_SIGNATURE =
  '0x1502ec7e795ed9c96b215e80d46d87e26141bc8d41f69ee1bfbc8d8ed9a700db62136da8ee35eadbfd678817342444dff0239508be51c1fae55d62fcdba2867e1b';
export const MOCK_EMAIL = 'test@example.com';
export const MOCK_PASSWORD = 'password123';
export const MOCK_HASHED_PASSWORD = 'hashedPassword';
export const MOCK_PAYMENT_ID = 'payment123';
export const MOCK_ACCESS_TOKEN = 'access_token';
export const MOCK_REFRESH_TOKEN = 'refresh_token';
export const MOCK_EXPIRES_IN = 1000000000000000;

export const MOCK_SENDGRID_API_KEY =
  'SG.xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
export const MOCK_PAYMENT_PROVIDER_SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxx';
export const MOCK_PAYMENT_PROVIDER_API_VERSION = '2022-11-15';
export const MOCK_PAYMENT_PROVIDER_APP_INFO_URL = 'https://test-app-url.com';
export const MOCK_SENDGRID_FROM_EMAIL = 'info@hmt.ai';
export const MOCK_SENDGRID_FROM_NAME = 'John Doe';
export const MOCK_S3_ENDPOINT = 'localhost';
export const MOCK_S3_PORT = 9000;
export const MOCK_S3_ACCESS_KEY = 'access_key';
export const MOCK_S3_SECRET_KEY = 'secret_key';
export const MOCK_S3_BUCKET = 'solution';
export const MOCK_S3_USE_SSL = false;
export const MOCK_MANIFEST: FortuneManifestDto = {
  submissionsRequired: 2,
  requesterTitle: 'Fortune',
  requesterDescription: 'Some desc',
  fundAmount: 10,
  requestType: FortuneJobType.FORTUNE,
};

export const MOCK_ENCRYPTED_MANIFEST = 'encryptedManifest';
export const MOCK_PGP_PRIVATE_KEY = `-----BEGIN PGP PRIVATE KEY BLOCK-----

xVgEZS6w6BYJKwYBBAHaRw8BAQdAXRzFR1ROwdb4Bu7RKYXcBvJsH6JmBxiT
Zwbnk3KUBiUAAP9N8d16MWV/M+yggH6cTODDCNCDV/Ic012RP0fTI4VEjhFF
zRtKb2IgTGF1bmNoZXIgPGFkbWluQGhtdC5haT7CjAQQFgoAPgWCZS6w6AQL
CQcICZBAfiPaLRaJeAMVCAoEFgACAQIZAQKbAwIeARYhBNvDQnyGS7m0aAs+
BUB+I9otFol4AACYcAEA/c1peyz3aWsB9NkvOfy/erdqkNAAHfikCKzGRKtD
sKcA/Rk9IHYRBzrvXyXXpFYkeFR1H6dXTUYzoZy8xoFleSIOx10EZS6w6BIK
KwYBBAGXVQEFAQEHQPOpvDe3nptX0ZqcFsUz/K7HHnSSOIn/aGYfrZfKAwQ1
AwEIBwAA/3fQjUAKIaoDAQTB2Jufw9g1JBybjMXSb3YCWunTB6ZgD5vCeAQY
FggAKgWCZS6w6AmQQH4j2i0WiXgCmwwWIQTbw0J8hku5tGgLPgVAfiPaLRaJ
eAAAYHMBAPI7LdZ8k4lQBvlXjVMV3hlkQGtKp+EXHd3BaT1hpniVAP4wecxi
7jxPB0Thko1w1Ro6ZYsFtlOB52qocYtduLJkCA==
=qV+I
-----END PGP PRIVATE KEY BLOCK-----`;

export const MOCK_PGP_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEZS6w6BYJKwYBBAHaRw8BAQdAXRzFR1ROwdb4Bu7RKYXcBvJsH6JmBxiT
Zwbnk3KUBiXNG0pvYiBMYXVuY2hlciA8YWRtaW5AaG10LmFpPsKMBBAWCgA+
BYJlLrDoBAsJBwgJkEB+I9otFol4AxUICgQWAAIBAhkBApsDAh4BFiEE28NC
fIZLubRoCz4FQH4j2i0WiXgAAJhwAQD9zWl7LPdpawH02S85/L96t2qQ0AAd
+KQIrMZEq0OwpwD9GT0gdhEHOu9fJdekViR4VHUfp1dNRjOhnLzGgWV5Ig7O
OARlLrDoEgorBgEEAZdVAQUBAQdA86m8N7eem1fRmpwWxTP8rscedJI4if9o
Zh+tl8oDBDUDAQgHwngEGBYIACoFgmUusOgJkEB+I9otFol4ApsMFiEE28NC
fIZLubRoCz4FQH4j2i0WiXgAAGBzAQDyOy3WfJOJUAb5V41TFd4ZZEBrSqfh
Fx3dwWk9YaZ4lQD+MHnMYu48TwdE4ZKNcNUaOmWLBbZTgedqqHGLXbiyZAg=
=IMAe
-----END PGP PUBLIC KEY BLOCK-----`;
export const MOCK_PGP_PASSPHRASE = '';
export const MOCK_HCAPTCHA_SITE_KEY = '1234';
export const MOCK_MAX_RETRY_COUNT = 5;
export const MOCK_RATE_CACHE_TIME = 30;
export const MOCK_FE_URL = 'http://localhost:3001';

export const mockConfig: any = {
  RATE_CACHE_TIME: MOCK_RATE_CACHE_TIME,
  S3_ACCESS_KEY: MOCK_S3_ACCESS_KEY,
  S3_SECRET_KEY: MOCK_S3_SECRET_KEY,
  S3_ENDPOINT: MOCK_S3_ENDPOINT,
  S3_PORT: MOCK_S3_PORT,
  S3_USE_SSL: MOCK_S3_USE_SSL,
  S3_BUCKET: MOCK_S3_BUCKET,
  PGP_ENCRYPT: false,
  PGP_PRIVATE_KEY: MOCK_PGP_PRIVATE_KEY,
  PGP_PASSPHRASE: MOCK_PGP_PASSPHRASE,
  REPUTATION_ORACLE_ADDRESS: MOCK_ADDRESS,
  WEB3_PRIVATE_KEY: MOCK_PRIVATE_KEY,
  PAYMENT_PROVIDER_SECRET_KEY: MOCK_PAYMENT_PROVIDER_SECRET_KEY,
  PAYMENT_PROVIDER_API_VERSION: MOCK_PAYMENT_PROVIDER_API_VERSION,
  PAYMENT_PROVIDER_APP_INFO_URL: MOCK_PAYMENT_PROVIDER_APP_INFO_URL,
  HCAPTCHA_SITE_KEY: MOCK_HCAPTCHA_SITE_KEY,
  HCAPTCHA_RECORDING_ORACLE_URI: MOCK_RECORDING_ORACLE_URL,
  HCAPTCHA_REPUTATION_ORACLE_URI: MOCK_REPUTATION_ORACLE_URL,
  HCAPTCHA_ORACLE_ADDRESS: MOCK_ADDRESS,
  HCAPTCHA_SECRET: MOCK_SECRET,
  JWT_ACCESS_TOKEN_EXPIRES_IN: MOCK_EXPIRES_IN,
  MAX_RETRY_COUNT: MOCK_MAX_RETRY_COUNT,
  RPC_URL_POLYGON_AMOY: MOCK_WEB3_RPC_URL,
  SENDGRID_API_KEY: MOCK_SENDGRID_API_KEY,
  SENDGRID_FROM_EMAIL: MOCK_SENDGRID_FROM_EMAIL,
  SENDGRID_FROM_NAME: MOCK_SENDGRID_FROM_NAME,
  WEB3_ENV: Web3Env.TESTNET,
  FE_URL: MOCK_FE_URL,
};
