import { Web3Env } from '../src/common/enums/web3';

export const MOCK_REQUESTER_TITLE = 'Mock job title';
export const MOCK_REQUESTER_DESCRIPTION = 'Mock job description';
export const MOCK_ADDRESS = '0xCf88b3f1992458C2f5a229573c768D0E9F70C44e';
export const MOCK_FILE_URL = 'http://local.test/some-mocked-file-url';
export const MOCK_WEBHOOK_URL = 'mockedWebhookUrl';
export const MOCK_FILE_HASH = 'mockedFileHash';
export const MOCK_FILE_KEY = 'manifest.json';
export const MOCK_LABEL = 'contains burnt area';
export const MOCK_LABEL_NEGATIVE = '';
export const MOCK_RECORDING_ORACLE_FEE = 5;
export const MOCK_REPUTATION_ORACLE_FEE = 5;
export const MOCK_JOB_LAUNCHER_ADDRESS =
  '0xCf88b3f1992458C2f5a229573c768D0E9F70C441';
export const MOCK_EXCHANGE_ORACLE_ADDRESS =
  '0xCf88b3f1992458C2f5a229573c768D0E9F70C441';
export const MOCK_RECORDING_ORACLE_ADDRESS =
  '0xCf88b3f1992458C2f5a229573c768D0E9F70C442';
export const MOCK_REPUTATION_ORACLE_ADDRESS =
  '0xCf88b3f1992458C2f5a229573c768D0E9F70C443';
export const MOCK_PRIVATE_KEY =
  'd334daf65a631f40549cc7de126d5a0016f32a2d00c49f94563f9737f7135e55';
export const MOCK_PGP_PRIVATE_KEY = `
-----BEGIN PGP PRIVATE KEY BLOCK-----

lQOYBGD1Xl8BCAC1vL3mnVZ2S2Ooz1GF6bkxKZR8G+yYQOITriLZ5YXQQyzTveVl
mYk1mkIaWjFJHQ4tTT1cJe5Og6WV2ycRo5EhHzvXw5bAhdDkLHPQEKyRgIUG8IQC
FjGp13DtiY8P2zNL5eMxGiMTp8xQJ7jC3HVZROqUOujcdLPglfE7b5n/Ao9TBwFO
...
...
-----END PGP PRIVATE KEY BLOCK-----
`;

export const MOCK_PGP_PASSPHRASE = 'secure-passphrase';
export const MOCK_EMAIL = 'test@example.com';
export const MOCK_PASSWORD = 'password123';
export const MOCK_HASHED_PASSWORD =
  '$2b$12$Z02o9/Ay7CT0n99icApZYORH8iJI9VGtl3mju7d0c4SdDDujhSzOa';
export const MOCK_ACCESS_TOKEN = 'access_token';
export const MOCK_REFRESH_TOKEN = 'refresh_token';
export const MOCK_ACCESS_TOKEN_HASHED = 'access_token_hashed';
export const MOCK_REFRESH_TOKEN_HASHED = 'refresh_token_hashed';
export const MOCK_EXPIRES_IN = 300000;
export const MOCK_SENDGRID_API_KEY =
  'SG.xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
export const MOCK_SENDGRID_FROM_EMAIL = 'info@hmt.ai';
export const MOCK_SENDGRID_FROM_NAME = 'John Doe';

export const MOCK_S3_ENDPOINT = 'localhost';
export const MOCK_S3_PORT = 9000;
export const MOCK_S3_ACCESS_KEY = 'access_key';
export const MOCK_S3_SECRET_KEY = 'secret_key';
export const MOCK_S3_BUCKET = 'solution';
export const MOCK_S3_USE_SSL = false;

export const MOCK_ENCRYPTION_PRIVATE_KEY = `-----BEGIN PGP PRIVATE KEY BLOCK-----

xVgEZS6w6BYJKwYBBAHaRw8BAQdAXRzFR1ROwdb4Bu7RKYXcBvJsH6JmBxiT
Zwbnk3KUBiUAAP9N8d16MWV/M+yggH6cTODDCNCDV/Ic012RP0fTI4VEjhFF
zRtKb2IgTGF1bmNoZXIgPGFkbWluQGhtdC5haT7CjAQQFgoAPgWCZS6w6AQL
CQcICZBAfiPaLRaJeAMVCAoEFgACAQIZAQKbAwIeARYhBNvDQnyGS7m0aAs+
BUB+I9otFol4AACYcAEA/c1peyz3aWsB9NkvOfy/erdqkNAAHfikCKzGRKtD
sKcA/Rk9IHYRBzrvXyXXpFYkeFR1H6dXTUYzoZy8xoFleSIOx10EZS6w6BIK
KwYBBAGXVQEFAQEHQPOpvDe3nptX0ZqcFsUz/K7HHnSSOIn/aGYfrZfKAwQ1
AwEIBwAA/3fQjUAKIaoDAQTB2Jufw9g1JBybjMXSb3YCWunTB6ZgD5vCeAQY
FggAKgWCZS6w6AmQQH4j2i0WiXgCmwwWIQTbw0J8hku5tGgLPgVAfiPaLRaJ
eAAAYHMBAPI7LdZ8k4lQBvlXjVMV3hlkQGtKp+EXHd3BaT1hpniVAP4wecxi
7jxPB0Thko1w1Ro6ZYsFtlOB52qocYtduLJkCA==
=qV+I
-----END PGP PRIVATE KEY BLOCK-----`;

export const MOCK_ENCRYPTION_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEZS6w6BYJKwYBBAHaRw8BAQdAXRzFR1ROwdb4Bu7RKYXcBvJsH6JmBxiT
Zwbnk3KUBiXNG0pvYiBMYXVuY2hlciA8YWRtaW5AaG10LmFpPsKMBBAWCgA+
BYJlLrDoBAsJBwgJkEB+I9otFol4AxUICgQWAAIBAhkBApsDAh4BFiEE28NC
fIZLubRoCz4FQH4j2i0WiXgAAJhwAQD9zWl7LPdpawH02S85/L96t2qQ0AAd
+KQIrMZEq0OwpwD9GT0gdhEHOu9fJdekViR4VHUfp1dNRjOhnLzGgWV5Ig7O
OARlLrDoEgorBgEEAZdVAQUBAQdA86m8N7eem1fRmpwWxTP8rscedJI4if9o
Zh+tl8oDBDUDAQgHwngEGBYIACoFgmUusOgJkEB+I9otFol4ApsMFiEE28NC
fIZLubRoCz4FQH4j2i0WiXgAAGBzAQDyOy3WfJOJUAb5V41TFd4ZZEBrSqfh
Fx3dwWk9YaZ4lQD+MHnMYu48TwdE4ZKNcNUaOmWLBbZTgedqqHGLXbiyZAg=
=IMAe
-----END PGP PUBLIC KEY BLOCK-----`;
export const MOCK_MAX_RETRY_COUNT = 5;
export const MOCK_BUCKET_FILE =
  'https://bucket.s3.eu-central-1.amazonaws.com/folder/test';

export const MOCK_HCAPTCHA_SITE_KEY = 'site-key';
export const MOCK_HCAPTCHA_API_KEY = 'api-key';
export const MOCK_HCAPTCHA_TOKEN = 'test-token';
export const MOCK_HCAPTCHA_SECRET = 'secret';
export const MOCK_HCAPTCHA_DEFAULT_LABELER_LANG = 'en';
export const MOCK_HCAPTCHA_PROTECTION_URL = 'https://api.hcaptcha.com';
export const MOCK_HCAPTCHA_LABELING_URL = 'https://foundation-accounts.hmt.ai';
export const MOCK_WEB3_RPC_URL = 'http://localhost:8545';
export const MOCK_QUALIFICATION_MIN_VALIDITY = 100;
export const MOCK_FE_URL = 'http://localhost:3001';
export const MOCK_KYC_API_PRIVATE_KEY = 'api-private-key';

export const mockConfig: any = {
  S3_ACCESS_KEY: MOCK_S3_ACCESS_KEY,
  S3_SECRET_KEY: MOCK_S3_SECRET_KEY,
  S3_ENDPOINT: MOCK_S3_ENDPOINT,
  S3_PORT: MOCK_S3_PORT,
  S3_USE_SSL: MOCK_S3_USE_SSL,
  S3_BUCKET: MOCK_S3_BUCKET,
  PGP_ENCRYPT: false,
  PGP_PRIVATE_KEY: MOCK_PGP_PRIVATE_KEY,
  PGP_PASSPHRASE: MOCK_PGP_PASSPHRASE,
  WEB3_PRIVATE_KEY: MOCK_PRIVATE_KEY,
  REPUTATION_LEVEL_LOW: 300,
  REPUTATION_LEVEL_HIGH: 700,
  JWT_ACCESS_TOKEN_EXPIRES_IN: MOCK_EXPIRES_IN,
  MAX_RETRY_COUNT: MOCK_MAX_RETRY_COUNT,
  RPC_URL_POLYGON_AMOY: MOCK_WEB3_RPC_URL,
  SENDGRID_API_KEY: MOCK_SENDGRID_API_KEY,
  SENDGRID_FROM_EMAIL: MOCK_SENDGRID_FROM_EMAIL,
  SENDGRID_FROM_NAME: MOCK_SENDGRID_FROM_NAME,
  WEB3_ENV: Web3Env.TESTNET,
  QUALIFICATION_MIN_VALIDITY: 1,
  FE_URL: MOCK_FE_URL,
  HCAPTCHA_SITE_KEY: MOCK_HCAPTCHA_SITE_KEY,
  HCAPTCHA_API_KEY: MOCK_HCAPTCHA_API_KEY,
  HCAPTCHA_SECRET: MOCK_HCAPTCHA_SECRET,
  HCAPTCHA_PROTECTION_URL: MOCK_HCAPTCHA_PROTECTION_URL,
  HCAPTCHA_LABELING_URL: MOCK_HCAPTCHA_LABELING_URL,
  HCAPTCHA_DEFAULT_LABELER_LANG: MOCK_HCAPTCHA_DEFAULT_LABELER_LANG,
  KYC_API_PRIVATE_KEY: MOCK_KYC_API_PRIVATE_KEY,
};

export const MOCK_BACKOFF_INTERVAL_SECONDS = 120;
