import { KVStoreClient, KVStoreKeys, Role } from '@human-protocol/sdk';
import { Wallet, ethers } from 'ethers';

export async function setup(): Promise<void> {
  //This private key is generated by hardhat and should be used just for local testing
  const privateKey =
    '0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a'; //0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
  const provider = new ethers.JsonRpcProvider('http://localhost:8545');
  const wallet = new Wallet(privateKey, provider);

  const kvStoreClient = await KVStoreClient.build(wallet);
  await kvStoreClient.setBulk(
    [KVStoreKeys.role, KVStoreKeys.fee, KVStoreKeys.webhookUrl],
    [Role.ReputationOracle, '1', 'http://localhost:5003/webhook'],
  );
}

setup();
