export enum MyJobStatus {
  ACTIVE = 'ACTIVE',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED',
  VALIDATION = 'VALIDATION',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
}

export const UNKNOWN_JOB_STATUS = 'UNKNOWN';
