"""add_task_iterations

Revision ID: 00271dfae3b1
Revises: a0c5c3a4c13f
Create Date: 2024-05-08 18:48:53.897599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00271dfae3b1'
down_revision = 'a0c5c3a4c13f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('iteration', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'iteration')
    # ### end Alembic commands ###
