"""add_gt_labels_in_gt_stats

Revision ID: 1e89224ad721
Revises: 76f0bc042477
Create Date: 2025-01-08 14:24:35.704162

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e89224ad721"
down_revision = "76f0bc042477"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gt_stats", sa.Column("label_set", sa.String(), nullable=False, server_default="")
    )
    # ### end Alembic commands ###

    op.alter_column("gt_stats", "label_set", existing_server_default="", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gt_stats", "label_set")
    # ### end Alembic commands ###
