"""Add cleaned_at

Revision ID: e994bc3d79ea
Revises: 00271dfae3b1
Create Date: 2024-08-26 10:59:14.459058

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e994bc3d79ea"
down_revision = "00271dfae3b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "cleaned_at")
    # ### end Alembic commands ###
