import os
from collections.abc import Generator
from dataclasses import dataclass
from io import StringIO
from pathlib import Path

os.environ["DEBUG"] = "1"

import pytest
from alembic.config import Config
from fastapi.testclient import TestClient
from sqlalchemy import TextClause, inspect, text
from sqlalchemy.orm import Session
from sqlalchemy_utils import create_database, database_exists, drop_database

from alembic import command as alembic_command
from alembic.config import Config
from src.apps.exchange_oracle import app
from src.db import Base, SessionLocal, engine

alembic_config = Config(Path(__file__).parent.parent / "alembic.ini")
# Don't let Alembic's fileConfig() disable the app's loggers when migrations run in-process,
# otherwise swallowed cron/webhook handler errors are hidden from the pytest report.
alembic_config.attributes["disable_existing_loggers"] = False


@dataclass
class AlembicSQL:
    upgrade: TextClause
    downgrade: TextClause


@pytest.fixture(scope="session")
def alembic() -> AlembicSQL:
    """
    Captures the SQL generated by Alembic for upgrade/downgrade operations.
    Doesn't actually run migrations.
    """
    alembic_config.output_buffer = StringIO()
    alembic_command.upgrade(alembic_config, "head", sql=True)
    upgrade_sql = alembic_config.output_buffer.getvalue()

    alembic_config.output_buffer = StringIO()
    alembic_command.downgrade(alembic_config, "head:base", sql=True)
    downgrade_sql = alembic_config.output_buffer.getvalue()

    return AlembicSQL(text(upgrade_sql), text(downgrade_sql))


@pytest.fixture(scope="session", autouse=True)
def setup_db(alembic) -> None:
    assert "test" in engine.url.database, "The test database must be used for testing."
    if database_exists(engine.url):
        drop_database(engine.url)
    create_database(engine.url)

    # Apply the schema once for the whole session. Per-test resets only truncate the DB.
    try:
        with engine.connect() as connection:
            # Validate the migration round-trip once
            connection.execute(alembic.upgrade)
            connection.execute(alembic.downgrade)

            connection.execute(alembic.upgrade)
    except Exception as e:
        raise RuntimeError(
            "Alembic migrations must upgrade and downgrade cleanly "
            "(`alembic upgrade head` / `alembic downgrade base`). Fix the migrations."
        ) from e

    # The per-test cleanup only DELETEs rows; it does not reset sequences. Guard that assumption so
    # that a future migration adding a serial/identity column fails loudly here rather than silently
    # leaking sequence state (e.g. auto-increment ids) across tests.
    sequences = inspect(engine).get_sequence_names()
    assert not sequences, (
        f"Found DB sequences {sequences}: the per-test cleanup DELETEs rows without resetting "
        "sequences, so ids would leak between tests. Reset them per test (e.g. TRUNCATE ... "
        "RESTART IDENTITY, or ALTER SEQUENCE) and update the cleanup."
    )


# Clear every table between tests. DELETE in reverse dependency order is dramatically faster than
# TRUNCATE on this schema: TRUNCATE does per-table file truncation + fsync (~270ms for all tables),
# while DELETE on already-empty tables is ~0. No table uses an autoincrement primary key, so there
# are no sequences to reset (guarded in setup_db). Each DELETE is a single SQL expression.
_CLEANUP_SQL = text(
    ";\n".join(
        str(table.delete().compile(dialect=engine.dialect))
        for table in reversed(Base.metadata.sorted_tables)
    )
)


@pytest.fixture(autouse=True)
def init_db() -> None:
    """Reset the database to an empty, migrated schema before each test."""
    with engine.begin() as connection:
        connection.execute(_CLEANUP_SQL)


@pytest.fixture(scope="module")
def client() -> Generator:
    with TestClient(app) as c:
        yield c


@pytest.fixture
def session() -> Generator[Session, None, None]:
    session = SessionLocal()

    try:
        yield session
    finally:
        session.rollback()
        session.close()
