repos:
  -   repo: https://github.com/ambv/black
      rev: 22.6.0
      hooks:
        - id: black
          language_version: python3.10
  -   repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        - id: isort
          language_version: python3.11