"""Add escrow creation tracking

Revision ID: 0f3fb7bfcbcf
Revises: c1e74c227cfe
Create Date: 2024-04-12 18:51:51.504971

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0f3fb7bfcbcf'
down_revision = 'c1e74c227cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow_creations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('escrow_address', sa.String(length=42), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_creations_escrow_address'), 'escrow_creations', ['escrow_address'], unique=False)
    op.create_index(op.f('ix_escrow_creations_id'), 'escrow_creations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrow_creations_id'), table_name='escrow_creations')
    op.drop_index(op.f('ix_escrow_creations_escrow_address'), table_name='escrow_creations')
    op.drop_table('escrow_creations')
    # ### end Alembic commands ###
