"""init

Revision ID: 16ecc586d685
Revises:
Create Date: 2023-10-05 13:56:16.966151

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "16ecc586d685"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cvat_id", sa.Integer(), nullable=False),
        sa.Column("cvat_cloudstorage_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("escrow_address", sa.String(length=42), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("bucket_url", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cvat_webhook_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("escrow_address"),
    )
    op.create_index(
        op.f("ix_projects_cvat_cloudstorage_id"), "projects", ["cvat_cloudstorage_id"], unique=False
    )
    op.create_index(op.f("ix_projects_cvat_id"), "projects", ["cvat_id"], unique=True)
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("wallet_address", sa.String(), nullable=False),
        sa.Column("cvat_email", sa.String(), nullable=True),
        sa.Column("cvat_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("wallet_address"),
    )
    op.create_index(op.f("ix_users_cvat_email"), "users", ["cvat_email"], unique=True)
    op.create_index(op.f("ix_users_cvat_id"), "users", ["cvat_id"], unique=True)
    op.create_index(op.f("ix_users_wallet_address"), "users", ["wallet_address"], unique=False)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=True),
        sa.Column("escrow_address", sa.String(length=42), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "wait_until", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("direction", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_id"), "webhooks", ["id"], unique=False)
    op.create_index(op.f("ix_webhooks_signature"), "webhooks", ["signature"], unique=True)
    op.create_table(
        "images",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cvat_project_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["cvat_project_id"], ["projects.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cvat_project_id", "filename", name="_project_filename_uc"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cvat_id", sa.Integer(), nullable=False),
        sa.Column("cvat_project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cvat_project_id"], ["projects.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_cvat_id"), "tasks", ["cvat_id"], unique=True)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_table(
        "data_uploads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_uploads_id"), "data_uploads", ["id"], unique=False)
    op.create_index(op.f("ix_data_uploads_task_id"), "data_uploads", ["task_id"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cvat_id", sa.Integer(), nullable=False),
        sa.Column("cvat_task_id", sa.Integer(), nullable=False),
        sa.Column("cvat_project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cvat_project_id"], ["projects.cvat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cvat_task_id"], ["tasks.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_cvat_id"), "jobs", ["cvat_id"], unique=True)
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_wallet_address", sa.String(), nullable=False),
        sa.Column("cvat_job_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), server_default="created", nullable=False),
        sa.ForeignKeyConstraint(["cvat_job_id"], ["jobs.cvat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_wallet_address"], ["users.wallet_address"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_id"), "assignments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assignments_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_cvat_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_data_uploads_task_id"), table_name="data_uploads")
    op.drop_index(op.f("ix_data_uploads_id"), table_name="data_uploads")
    op.drop_table("data_uploads")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_cvat_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_webhooks_signature"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_users_wallet_address"), table_name="users")
    op.drop_index(op.f("ix_users_cvat_id"), table_name="users")
    op.drop_index(op.f("ix_users_cvat_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_cvat_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_cvat_cloudstorage_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
