"""Add escrow_validations

Revision ID: fde2b09b6b39
Revises: 0f3fb7bfcbcf
Create Date: 2024-09-25 03:39:38.552595

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fde2b09b6b39"
down_revision = "2cbc85686054"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escrow_validations",
        sa.Column("id", sa.String(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("escrow_address", sa.String(length=42), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("escrow_address", "chain_id", name="uix_escrow_chain"),
    )
    op.create_index(
        op.f("ix_escrow_validations_escrow_address"),
        "escrow_validations",
        ["escrow_address"],
        unique=False,
    )
    op.create_index(op.f("ix_escrow_validations_id"), "escrow_validations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escrow_validations_id"), table_name="escrow_validations")
    op.drop_index(op.f("ix_escrow_validations_escrow_address"), table_name="escrow_validations")
    op.drop_table("escrow_validations")
    # ### end Alembic commands ###
