"""job_start_stop_frame

Revision ID: 0a91b6a5f7b6
Revises: fde2b09b6b39
Create Date: 2024-11-07 08:15:00.780982

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a91b6a5f7b6"
down_revision = "fde2b09b6b39"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("start_frame", sa.Integer(), nullable=False))
    op.add_column("jobs", sa.Column("stop_frame", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "stop_frame")
    op.drop_column("jobs", "start_frame")
    # ### end Alembic commands ###
