"""
Add CVAT webhook queue

Revision ID: 216af22b5590
Revises: c32b36a87539
Create Date: 2025-09-09 20:08:23.474046

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "216af22b5590"
down_revision = "c32b36a87539"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "cvat_webhooks",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("cvat_project_id", sa.Integer(), nullable=False),
        sa.Column("cvat_task_id", sa.Integer(), nullable=False),
        sa.Column("cvat_job_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "wait_until", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["cvat_job_id"], ["jobs.cvat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cvat_project_id"], ["projects.cvat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cvat_task_id"], ["tasks.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cvat_webhooks_cvat_job_id"), "cvat_webhooks", ["cvat_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_cvat_webhooks_cvat_project_id"), "cvat_webhooks", ["cvat_project_id"], unique=False
    )
    op.create_index(
        op.f("ix_cvat_webhooks_cvat_task_id"), "cvat_webhooks", ["cvat_task_id"], unique=False
    )
    op.create_index(op.f("ix_cvat_webhooks_id"), "cvat_webhooks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_cvat_webhooks_id"), table_name="cvat_webhooks")
    op.drop_index(op.f("ix_cvat_webhooks_cvat_task_id"), table_name="cvat_webhooks")
    op.drop_index(op.f("ix_cvat_webhooks_cvat_project_id"), table_name="cvat_webhooks")
    op.drop_index(op.f("ix_cvat_webhooks_cvat_job_id"), table_name="cvat_webhooks")
    op.drop_table("cvat_webhooks")
    # ### end Alembic commands ###
