"""
add project assignment_bounty

Revision ID: 9884511c7077
Revises: 216af22b5590
Create Date: 2026-07-15 14:31:16.493245

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9884511c7077"
down_revision = "216af22b5590"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("assignment_bounty", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "assignment_bounty")
    # ### end Alembic commands ###
