"""non-unique-escrows

Revision ID: c1e74c227cfe
Revises: 16ecc586d685
Create Date: 2024-02-05 22:54:42.478270

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c1e74c227cfe'
down_revision = '16ecc586d685'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_escrow_address_key', 'projects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('projects_escrow_address_key', 'projects', ['escrow_address'])
    # ### end Alembic commands ###
