export enum ReputationEntityType {
  WORKER = 'WORKER',
  JOB_LAUNCHER = 'JOB_LAUNCHER',
  EXCHANGE_ORACLE = 'EXCHANGE_ORACLE',
  RECORDING_ORACLE = 'RECORDING_ORACLE',
  REPUTATION_ORACLE = 'REPUTATION_ORACLE',
  CREDENTIAL_VALIDATOR = 'CREDENTIAL_VALIDATOR',
}

export enum ReputationLevel {
  LOW = 'Low',
  MEDIUM = 'Medium',
  HIGH = 'High',
}
