export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum Role {
  OPERATOR = 'OPERATOR',
  WORKER = 'WORKER',
  HUMAN_APP = 'HUMAN_APP',
  ADMIN = 'ADMIN',
}

export enum KycStatus {
  NONE = 'NONE',
  APPROVED = 'APPROVED',
  SUBMISSION_REQUIRED = 'SUBMISSION_REQUIRED',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
  REJECTED = 'REJECTED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  RESET = 'RESET',
  ERROR = 'ERROR',
}

export enum KycServiceType {
  ID_DOCUMENT = 'ID_DOCUMENT',
  LIVENESS = 'LIVENESS',
  PHONE = 'PHONE',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  EMAIL = 'EMAIL',
  AML = 'AML',
  DUPLICATE = 'DUPLICATE',
}

export enum OperatorStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
