export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum UserType {
  OPERATOR = 'OPERATOR',
  EXCHANGE_ORACLE = 'EXCHANGE_ORACLE',
  RECORDING_ORACLE = 'RECORDING_ORACLE',
  WORKER = 'WORKER',
}

export enum KycStatus {
  NONE = 'NONE',
  APPROVED = 'APPROVED',
  SUBMISSION_REQUIRED = 'SUBMISSION_REQUIRED',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
  REJECTED = 'REJECTED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  RESET = 'RESET',
}

export enum OperatorStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
