[workspace]

members = [

    # Common contract paths
    "contracts/common-structs",

    # Escrow contract paths
    "contracts/escrow",
    "contracts/escrow/meta",

    # Escrow factory contract paths
    "contracts/escrow-factory",
    "contracts/escrow-factory/meta",

    # KV Store contract paths
    "contracts/kv-store",
    "contracts/kv-store/meta",

    # Rewards pool contract paths
    "contracts/rewards-pool",
    "contracts/rewards-pool/meta",

    # Staking contract paths
    "contracts/staking",
    "contracts/staking/meta",

    # Staking mock contract paths
    "contracts/staking-mock",
    "contracts/staking-mock/meta",

    # Rewards pool mock contract paths
    "contracts/rewards-pool-mock",
    "contracts/rewards-pool-mock/meta",

    # Escrow mock contract paths
    "contracts/escrow-mock",
    "contracts/escrow-mock/meta",
]