export enum ReputationEntityType {
  LIQUIDITY_PROVIDER = 'LIQUIDITY_PROVIDER',
  JOB_LAUNCHER = 'JOB_LAUNCHER',
  EXCHANGE_ORACLE = 'EXCHANGE_ORACLE',
  RECORDING_ORACLE = 'RECORDING_ORACLE',
  REPUTATION_ORACLE = 'REPUTATION_ORACLE',
}

export enum ReputationLevel {
  LOW = 'Low',
  MEDIUM = 'Medium',
  HIGH = 'High',
}
