export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum UserType {
  OPERATOR = 'OPERATOR',
  EXCHANGE_ORACLE = 'EXCHANGE_ORACLE',
  RECORDING_ORACLE = 'RECORDING_ORACLE',
  WORKER = 'WORKER',
}
