export type EventDayData = {
  id: string;
  timestamp: number;
  dailyBulkPayoutEventCount: string;
  dailyCancelledStatusEventCount: string;
  dailyCompletedStatusEventCount: string;
  dailyEscrowCount: string;
  dailyFundEventCount: string;
  dailyHMTTransferAmount: string;
  dailyHMTTransferCount: string;
  dailyPaidStatusEventCount: string;
  dailyPartialStatusEventCount: string;
  dailyPayoutAmount: string;
  dailyPayoutCount: string;
  dailyPendingStatusEventCount: string;
  dailySetupEventCount: string;
  dailyStoreResultsEventCount: string;
  dailyTotalEventCount: string;
  dailyWorkerCount: string;
};
