[workspace]

members = [

    # Escrow contract paths
    "contracts/escrow",
    "contracts/escrow/meta",

    # Escrow factory contract paths
    "contracts/escrow-factory",
    "contracts/escrow-factory/meta",

]