sync-python-changelog:
	cp -f packages/sdk/python/human-protocol-sdk/CHANGELOG.md packages/sdk/python/human-protocol-sdk/docs/CHANGELOG.md
sync-typescript-changelog:
	cp -f packages/sdk/typescript/human-protocol-sdk/CHANGELOG.md packages/sdk/typescript/human-protocol-sdk/docs/CHANGELOG.md