#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

cd packages/sdk/python
cd human-protocol-basemodels && make format && git add . -u
cd ..
cd human-protocol-sdk && make format && git add . -u
cd ../../../

