import { KVStoreClient, KVStoreKeys, Role } from '@human-protocol/sdk';
import { Wallet, ethers } from 'ethers';

export async function setup(): Promise<void> {
  //This private key is generated by hardhat and should be used just for local testing
  const privateKey =
    '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'; //0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
  const provider = new ethers.JsonRpcProvider('http://localhost:8545');
  const wallet = new Wallet(privateKey, provider);

  const kvStoreClient = await KVStoreClient.build(wallet);
  await kvStoreClient.setBulk(
    [KVStoreKeys.role, KVStoreKeys.fee, KVStoreKeys.webhookUrl],
    [Role.ExchangeOracle, '1', 'http://localhost:5001/webhook'],
  );
}
