name: Generate and Sync Contract ABIs

on:
  workflow_dispatch:

jobs:
  generate-and-sync-abis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_CD_CONTRACTS }}
      
      # Install dependencies 
      - name: Install dependencies
        run: npm install --global yarn && yarn --ignore-scripts
        working-directory: ./packages/core
      
      # Install node-jq 
      - name: Install node-jq
        run: npm install node-jq
        working-directory: ./packages/core

      # Build core package
      - name: Build core package
        run: yarn build
        working-directory: ./packages/core

      # Extract ABIs using node-jq
      - name: Extract ABIs
        run: |
          jq '.abi' artifacts/contracts/governance/MetaHumanGovernor.sol/MetaHumanGovernor.json > abis/MetaHumanGovernor.abi.json
          jq '.abi' artifacts/contracts/governance/DAOSpokeContract.sol/DAOSpokeContract.json > abis/DAOSpokeContract.abi.json
        working-directory: ./packages/core

      # Commit ABIs to the Repository
      - name: Commit ABIs to the Repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add abis/*
          git commit -m "Update ABIs for MetaHumanGovernor and DAOSpokeContract" || echo "No changes to commit"
          git push
        working-directory: ./packages/core

      # Sync ABIs to Governance Repository
      - name: Sync ABIs to Governance Repository
        run: |
          git clone https://github.com/humanprotocol/governance.git temp-governance-repo
          cp -a ./packages/core/abis/. temp-governance-repo/abis/
          cd temp-governance-repo
          git add .
          git commit -m "Sync ABIs for MetaHumanGovernor and DAOSpokeContract" || echo "No changes to ABIs"
          git push
