name: Human App Check

on:
  push:
    branches: "**"
    paths:
      - "packages/core/**"
      - "packages/sdk/typescript/human-protocol-sdk/**"
      - "packages/apps/human-app/**"

jobs:
  job-app-server-test:
    name: Human App Server Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn workspaces focus @apps/human-app-server
      - name: Build libs (scoped)
        run: yarn workspaces foreach -Rpt --from @apps/human-app-server run build
      - name: Run Job Human App unit tests
        run: yarn workspace @apps/human-app-server test
