name: Node.js Base Models check

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  node-basemodels-test:
    name: Node.js Base Models Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - run: yarn basemodels:test
        name: Run Node.js Base Models Test
