name: Fortune V3 check

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'packages/core/**'
      - 'packages/sdk/typescript/human-protocol-sdk/**'
      - 'packages/app/fortune/**'
  workflow_dispatch:

jobs:
  fortune-test:
    name: Fortune V3 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global yarn && yarn
        name: Install dependencies
      - run: yarn fortune-v3:test
        name: Run fortune V3 test
