name: Fortune check

on:
  push:
    branches: "**"
    paths:
      - "packages/core/**"
      - "packages/sdk/typescript/human-protocol-sdk/**"
      - "packages/apps/fortune/**"

jobs:
  fortune-exchange-oracle-test:
    name: Fortune Exchange Oracle Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn workspaces focus @apps/fortune-exchange-oracle-server
      - name: Build libs (scoped)
        run: yarn workspaces foreach -Rpt --from @apps/fortune-exchange-oracle-server run build
      - name: Run Exchange Oracle tests
        run: yarn workspace @apps/fortune-exchange-oracle-server test

  fortune-recording-oracle-test:
    name: Fortune Recording Oracle Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn workspaces focus @apps/fortune-recording-oracle
      - name: Build libs (scoped)
        run: yarn workspaces foreach -Rpt --from @apps/fortune-recording-oracle run build
      - name: Run Recording Oracle tests
        run: yarn workspace @apps/fortune-recording-oracle test
