name: Node.js SDK check

on:
  push:
    branches: "**"
    paths:
      - "packages/core/**"
      - "packages/sdk/typescript/human-protocol-sdk/**"

jobs:
  node-sdk-test:
    name: Node.js SDK Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn workspaces focus @human-protocol/sdk
      - name: Build packages (scoped)
        run: yarn workspaces foreach -Rpt --from @human-protocol/sdk run build
      - name: Run Node.js SDK test
        run: yarn workspace @human-protocol/sdk test
