name: Fortune V2 check

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  fortune-test:
    name: Fortune V2 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 #Temporal until this gets fixed https://github.com/NomicFoundation/hardhat/issues/3877
        with:
          node-version: 18.15
      - run: npm install --global yarn && yarn
        name: Install dependencies
      - run: yarn build
        name: Build core package
        working-directory: ./packages/core
      - run: yarn fortune-v2:test
        name: Run fortune V2 test
